import 'package:get/get.dart';

class LanguageUtil extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>
      {
        "en_US":{
          "English":"English",
          "简体中文":"Chinese",
          "email":"Email",
          "password":"Password",
          "login":"Login",
          "register":"Register",
          "select Language":"Select Language",
          "version":"Version",
          "forgot password":"Forgot password",
          "verification Code":"Verification Code",
          "获取验证码":"Get verification code",
          "请输入邮箱":"Please enter your email address",
          "输入密码":"Input password",
          "两次密码不一致":"The two passwords are inconsistent",
          "确认密码":"Confirm Password",
          "我的":"My",
          "重置密码":"Reset Password",
          "扑克账号":"Poker account",
          "设置":"Setting",
          "免责声明":"Disclaimers",
          "帮助中心":"Help Center",
          "检查更新":"Check update",
          "消息":"Message",
          "修改密码":"Change Password",
          "确认":"Confirm",
          "请输入当前密码":"Please enter the current password",
          "请输入新密码":"Please enter a new password",
          "请重复输入新密码":"Please re-enter the new password",
          "主页":"homepage",
          "购买":"buy",
          "您的余额":"Your balance",
          "计费说明":"Billing Description",
          "今日战况":"Today's war situation",
          '游戏平台':"Game platform",
          "下载":"Download",
          "退出登录":"Log out",
          "在您使用我们的应用程序之前，您必须知道":"Before you use our app, you must to know",
          "这个应用程序上的信息仅用于娱乐目的，不应作为财务建议。":"The information on this app is for entertainment purposes only and is not to be taken as financial advice.",
          "虽然我们相信数学是正确的，但它可能是错误和/或过时的。":"Although we believe the math is correct, it could be wrong and/or out of date.",
          "波动在网上赌博中起着重要作用，结果会因人而异，差别很大。":"Variance plays a significant role in online gambling and results will vary widely from person to person.",
          "这里提到的任何结果或潜在收益都不是稳妥的。运气是一个因素，所以参考这个应用程序的建议，风险由你自己承担。":"Any results or potential earnings mentioned here are not typical. Luck is a factor so pursue the contents of this app at your own risk.",
          "网上赌博在你居住的地方可能不合法，所以请检查你的当地法律。":"Online gambling may not be legal where you live so please check with your local laws.",
          "本应用程序与我们支持的任何赌场或扑克室没有任何关联。":"This app is in no way affiliated with any of the casinos or poker rooms that our products support.",
          "使用我们的应用程序可能违反我们软件支持的扑克室的服务条款。": "Using our app may be against the Terms of Service of the poker rooms our software supports.",
          "您对潜在的资金损失承担全部责任，无论是赌博损失还是被您使用我们软件的游戏网站扣押的账户":"You bear the sole responsibility for potential loss of funds, be it from gambling losses or from account seizure by the gaming site that you use our software at.",
          "在任何情况下，我们都不会向您偿还任何资金损失。":"Under no circumstances will we reimburse you for any lost funds.",
          "功能":"Function",
          "费用":"Cost",
          "盈利":"Profit",
          "异常":"Abnormal",
          "PokerWinner是什么？":"What is PokerWinner?",
          "我们是一款真AI德州扑克辅助软件，基于非对称信息博弈理论和大数据算法，通过AI决策来实现牌局策略的GTO平衡。":"We are a real AI Texas Poker auxiliary software. Based on the asymmetric information game theory and big data algorithm, we can achieve the GTO balance of the game strategy through AI decision-making.",
          "PokerWinner可以做什么？":"What can PokerWinner do?",
          "我们可以给你的线上德州牌局提供AI策略辅助，自动代打功能。":"We can provide AI strategy assistance and automatic playing function for your online Texas card game.",
          "PokerWinner支持哪些平台？":"What platforms does PokerWinner support?",
          "目前我们支持微扑克、德扑圈、扑克王三个线上平台，后续会扩展更多平台。":"At present, we support three online platforms, namely, We Poker, Delphi Circle and Poker King. More platforms will be expanded in the future.",
          "PokerWinner可以试用吗？":"Can PokerWinner try it for free?",
          "抱歉，我们不支持免费试用。":"Sorry, we don't support free trial.",
          "PokerWinner支持的场次":"Sessions supported by PokerWinner",
          "我们支持线上平台的全部场次，但不同场次收费有所不同。":"We support all sessions on the online platform, but different sessions charge different fees.",
          "PokerWinner是否可以多开":"Can I open PokerWinner more",
          "可以，一个AI账号可以绑定多个平台多个游戏账号，同时进行游戏。":"Yes, one AI account can be bound to multiple platforms and multiple game accounts to play games at the same time.",
          "PokerWinner是否可以同时打不同平台":"Can PokerWinner play on different platforms at the same time",
          "可以的。":"tolerable.",
          "PokerWinner支持模拟器吗？":"Does PokerWinner support emulators?",
          "通常来说支持，如果使用模拟器出现了异常，请反馈给我们。我们会尽快修复。":"Generally, it is supported. If there is an exception when using the simulator, please give us a feedback. We will repair it as soon as possible.",
          "PokerWinner支持手机吗？":"Does PokerWinner support mobile phones?",
          "支持，但考虑到不同的手机兼容性与适配问题，我们强烈建议您使用模拟器进行游戏。":"Yes, but considering the compatibility and adaptation of different mobile phones, we strongly recommend that you use the simulator to play games.",
          "PokerWinner是否兼容H2N、HM3等主流数据统计软件？":"Is PokerWinner compatible with mainstream data statistics software such as H2N and HM3?",
          "我们并不反对您使用数据统计软件，但不保证在后续版本中三方的兼容性能否一直保持优良状态。":"We do not object to your using the data statistics software, but we do not guarantee that the compatibility of the three parties will remain good in subsequent versions.",
          "使用PokerWinner是否会被封号？":"Will I be banned for using PokerWinner?",
          "绝大多数线上扑克平台中使用AI辅助类软件都是违反用户条款的。请您合理规划游戏内容与时间。":"We haven't worked on anti-detection solution so please plan your game content and time wisely.",
          "PokerWinner如何使用？":"How can I use PokerWinner?",
          "第一步，打开PokerWinner软件，登录账号确保您有足够的余额。\n第二步、打开您希望进行游戏的平台开关。（您必须安装和我们软件兼容的平台APP版本）\n第三步、进入平台APP，正常登录账号进行游戏。您在牌局界面会看到我们的策略提示内容框。在每次轮到你行动时，AI会给到出牌策略。":"Step 1: Open the PokerWinner software and login, make sure you have positive account balance.\nStep 2. Turn on the switch for the poker room. (You must install the APP version of the platform compatible with our software)\nStep 3: Open the poker room app and login to start playing, you will see our advisory box in the game interface.",
          "PokerWinner能否自动代打":"Can PokerWinner automatically play for me?",
          "可以，但前期自动代打仅对部分符合条件的用户开放。":"Yes, but the automatic mode in earlier versions was only available to some qualified users.",
          "PokerWinner怎么收费?":"How does PokerWinner charge?",
          "我们按手收费，只要您坐下，并且完成一手游戏。无论您是否中途弃牌或者打到开牌。均会收取费用。不同的扑克场次收费会有不同。":"We charge by the hand, as long as you sit down and complete a hand. It doesn't matter if you fold in the middle or show down at the end. You will be charged a fee. Fees will vary by room level.",
          "我在扑克平台观战是否收费？":"Do I have to pay to watch the game in the poker room?",
          "观战不会收取费用。":"No fee will be charged for standing by.",
          "如何充值点数？":"How do I buy PokerWinner credits?",
          "在PokerWinner里可以使用USDT进行充值，或者找您的代理商购买激活码，并且在PokerWinner里输入使用。":"You can add credits to your account in PokerWinner with USDT or buy an activation code from your dealer and enter it in PokerWinner Apps.",
          "自动代打和只提供策略辅助收费是否有区别？":"Is there any difference between fees of PokerWinner with automated game and a strategy-only version?",
          "没有区别。收费只和平台与场次有关。":"There is no difference. The fees are only relevant to the poker rooms and game levels.",
          "PokerWinner胜率如何？":"What is PokerWinner's winning rate?",
          "我们相信数学与大数据，也相信我们的策略比绝大多数玩家更优秀。但考虑到运气成分，我们无法保证您的胜率，请自行评估。":"We believe in math and big data, and our strategy can beat most players. However, winning is not guaranteed for any random game. ",
          "PokerWinner收益不好需要退款":"PokerWinner needs a refund due to poor income",
          "抱歉，我们不接受退款申请。德州是个长期的数学游戏，短期的胜负波动是非常常见的，如果您无法承受，建议您选择较小的场次。":"Sorry, we do not accept refund applications. Texas is a long-term math game, and short-term fluctuations are very common. If you can't bear it, we suggest you choose smaller sessions.",
          "PokerWinner如何保证盈利？":"How does PokerWinner ensure profitability?",
          "我们无法保证您的盈利，但长期来看，使用AI辅助策略产品是可以盈利的。这个已经经过无数专业德州玩家的考验并证明。":"We can't guarantee your profitability, but in the long run, it is profitable to use AI auxiliary strategy products. This has been tested and proved by numerous professional Texas players.",
          "扑克平台更新了无法使用":"Poker platform has been updated and cannot be used",
          "我们会尽力确保AI产品的稳定性和可用性，如果遇到平台更新无法使用。请联系我们或者耐心等待一段时间。我们会尽快提供扑克平台更新游戏包体。":"We will try our best to ensure the stability and availability of AI products. If we encounter platform updates, we cannot use them. Please contact us or wait patiently for a while. We will provide the poker platform to update the game package as soon as possible.",
          "PokerWinner没有给我意见":"Poker Winner didn't give me any advice",
          "抱歉，可能因为网络问题或者我们的服务稳定性偶尔会出现一些策略失去响应。您可以尝试完全退出游戏与PokerWinner并且重新进入游戏。如果问题依然存在，请不要继续进行游戏。反馈给我们或者等待我们修复问题。":"Sorry, some strategies may occasionally lose response due to network problems or our service stability. You can try to completely exit the game and PokerWinner and re-enter the game. If the problem persists, please do not continue the game. Give us feedback or wait for us to fix the problem.",
          "我觉得AI策略不正确，我能否不听意见自己打牌":"I think the AI strategy is incorrect. Can I play cards without listening to my opinions",
          "可以，您可以关闭自动代打，并且不理会AI的策略自行操作。下一轮轮到你行动时，AI仍然会根据当前情况给出最新的策略。":"Yes, you can turn off automatic proxy printing and operate independently regardless of AI policies. When it's your turn to take action in the next round, AI will still give the latest strategy according to the current situation.",
          "为什么我不能打开自动代打功能？":"Why can't I turn on the automatic generation function?",
          "前期自动代打仅对部分符合条件的用户开放。如果您需要此功能，可以联系我们或者您的代理商。我们会为您开通。":"Early automatic printing is only available to some qualified users. If you need this function, you can contact us or your agent. We will open it for you.",
          "为什么AI会在不该弃牌的时候放弃？":"Why does AI give up when it shouldn't?",
          "AI算法是一套很复杂的理论，它不会单纯输出加注/跟注/弃牌的策略。而是通过混合策略的方式，有概率加注/跟注/弃牌。即使弃牌的概率很低，但也会出现。虽然这不符合人类理解的常识，但从数学角度考虑，此时弃牌的收益和加注/跟注后输掉的概率是相当的。":"AI algorithm is a very complex theory, which does not simply output the strategy of adding/following/discarding cards. It is a mixed strategy with probability to add/follow/discard. Even if the probability of discarding cards is very low, it will occur. Although this is not in line with the common sense of human understanding, from a mathematical point of view, at this time, the payoff from discarding the card and the probability of losing after raising/following the bet are equal.",
          "明明不合理的牌，为什么要下注？":"Why bet on unreasonable cards?",
          "原因有很多，但主要来源基本遵从最小防守频率和最大剥削理论，AI会选择一部分牌进行诈唬，期望获得对手的弃牌收益。":"There are many reasons, but the main source basically follows the minimum defense frequency and maximum exploitation theory. AI will choose some cards to bluff, hoping to obtain the opponent's discard profits.",
        },
        "zh_CN":{
          "English":"英语",
          "简体中文":"简体中文",
          "email":"电子邮箱",
          "password":"密码",
          "login":"登录",
          "register":"注册",
          "select Language":"选择语言",
          "version":"版本",
          "forgot password":"忘记密码",
          "verification Code":"验证码",
          "重置密码":"重置密码",
          "获取验证码":"获取验证码",
          "输入密码":"输入密码",
          "确认密码":"确认密码",
          "请输入邮箱":"请输入邮箱",
          "两次密码不一致":"两次密码不一致",
          "我的":"我的",
          "扑克账号":"扑克账号",
          "设置":"设置",
          "免责声明":"免责声明",
          "帮助中心":"帮助中心",
          "检查更新":"检查更新",
          "消息":"消息",
          "修改密码":"修改密码",
          "确认":"确认",
          "请输入当前密码":"请输入当前密码",
          "请输入新密码":"请输入新密码",
          "请重复输入新密码":"请重复输入新密码",
          "主页":"主页",
          "购买":"购买",
          "您的余额":"您的余额",
          "计费说明":"计费说明",
          "今日战况":"今日战况",
          '游戏平台':"游戏平台",
          "下载":"下载",
          "退出登录":"退出登录",
          "在您使用我们的应用程序之前，您必须知道":"在您使用我们的应用程序之前，您必须知道",
          "这个应用程序上的信息仅用于娱乐目的，不应作为财务建议。":"这个应用程序上的信息仅用于娱乐目的，不应作为财务建议。",
          "虽然我们相信数学是正确的，但它可能是错误和/或过时的。":"虽然我们相信数学是正确的，但它可能是错误和/或过时的。",
          "波动在网上赌博中起着重要作用，结果会因人而异，差别很大。":"波动在网上赌博中起着重要作用，结果会因人而异，差别很大。",
          "这里提到的任何结果或潜在收益都不是稳妥的。运气是一个因素，所以参考这个应用程序的建议，风险由你自己承担。":"这里提到的任何结果或潜在收益都不是稳妥的。运气是一个因素，所以参考这个应用程序的建议，风险由你自己承担。",
          "网上赌博在你居住的地方可能不合法，所以请检查你的当地法律。":"网上赌博在你居住的地方可能不合法，所以请检查你的当地法律。",
          "本应用程序与我们支持的任何赌场或扑克室没有任何关联。":"本应用程序与我们支持的任何赌场或扑克室没有任何关联。",
          "使用我们的应用程序可能违反我们软件支持的扑克室的服务条款。": "使用我们的应用程序可能违反我们软件支持的扑克室的服务条款。",
          "您对潜在的资金损失承担全部责任，无论是赌博损失还是被您使用我们软件的游戏网站扣押的账户":"您对潜在的资金损失承担全部责任，无论是赌博损失还是被您使用我们软件的游戏网站扣押的账户",
          "在任何情况下，我们都不会向您偿还任何资金损失。":"在任何情况下，我们都不会向您偿还任何资金损失。",
          "功能":"功能",
          "费用":"费用",
          "盈利":"盈利",
          "异常":"异常",
          "PokerWinner是什么？":"PokerWinner是什么？",
          "我们是一款真AI德州扑克辅助软件，基于非对称信息博弈理论和大数据算法，通过AI决策来实现牌局策略的GTO平衡。":"我们是一款真AI德州扑克辅助软件，基于非对称信息博弈理论和大数据算法，通过AI决策来实现牌局策略的GTO平衡。",
          "PokerWinner可以做什么？":"PokerWinner可以做什么？",
          "我们可以给你的线上德州牌局提供AI策略辅助，自动代打功能。":"我们可以给你的线上德州牌局提供AI策略辅助，自动代打功能。",
          "PokerWinner支持哪些平台？":"PokerWinner支持哪些平台？",
          "目前我们支持微扑克、德扑圈、扑克王三个线上平台，后续会扩展更多平台。":"目前我们支持微扑克、德扑圈、扑克王三个线上平台，后续会扩展更多平台。",
          "PokerWinner可以试用吗？":"PokerWinner可以试用吗？",
          "抱歉，我们不支持免费试用。":"抱歉，我们不支持免费试用。",
          "PokerWinner支持的场次":"PokerWinner支持的场次",
          "我们支持线上平台的全部场次，但不同场次收费有所不同。":"我们支持线上平台的全部场次，但不同场次收费有所不同。",
          "PokerWinner是否可以多开":"PokerWinner是否可以多开",
          "可以，一个AI账号可以绑定多个平台多个游戏账号，同时进行游戏。":"可以，一个AI账号可以绑定多个平台多个游戏账号，同时进行游戏。",
          "PokerWinner是否可以同时打不同平台":"PokerWinner是否可以同时打不同平台",
          "可以的。":"可以的。",
          "PokerWinner支持模拟器吗？":"PokerWinner支持模拟器吗？",
          "通常来说支持，如果使用模拟器出现了异常，请反馈给我们。我们会尽快修复。":"通常来说支持，如果使用模拟器出现了异常，请反馈给我们。我们会尽快修复。",
          "PokerWinner支持手机吗？":"PokerWinner支持手机吗？",
          "支持，但考虑到不同的手机兼容性与适配问题，我们强烈建议您使用模拟器进行游戏。":"支持，但考虑到不同的手机兼容性与适配问题，我们强烈建议您使用模拟器进行游戏。",
          "PokerWinner是否兼容H2N、HM3等主流数据统计软件？":"PokerWinner是否兼容H2N、HM3等主流数据统计软件？",
          "我们并不反对您使用数据统计软件，但不保证在后续版本中三方的兼容性能否一直保持优良状态。":"我们并不反对您使用数据统计软件，但不保证在后续版本中三方的兼容性能否一直保持优良状态。",
          "使用PokerWinner是否会被封号？":"使用PokerWinner是否会被封号？",
          "绝大多数线上扑克平台中使用AI辅助类软件都是违反用户条款的。请您合理规划游戏内容与时间。":"绝大多数线上扑克平台中使用AI辅助类软件都是违反用户条款的。请您合理规划游戏内容与时间。",
          "PokerWinner如何使用？":"PokerWinner如何使用？",
          "第一步，打开PokerWinner软件，登录账号确保您有足够的余额。\n第二步、打开您希望进行游戏的平台开关。（您必须安装和我们软件兼容的平台APP版本）\n第三步、进入平台APP，正常登录账号进行游戏。您在牌局界面会看到我们的策略提示内容框。在每次轮到你行动时，AI会给到出牌策略。":"第一步，打开PokerWinner软件，登录账号确保您有足够的余额。\n第二步、打开您希望进行游戏的平台开关。（您必须安装和我们软件兼容的平台APP版本）\n第三步、进入平台APP，正常登录账号进行游戏。您在牌局界面会看到我们的策略提示内容框。在每次轮到你行动时，AI会给到出牌策略。",
          "PokerWinner能否自动代打":"PokerWinner能否自动代打",
          "可以，但前期自动代打仅对部分符合条件的用户开放。":"可以，但前期自动代打仅对部分符合条件的用户开放。",
          "PokerWinner怎么收费?":"PokerWinner怎么收费?",
          "我们按手收费，只要您坐下，并且完成一手游戏。无论您是否中途弃牌或者打到开牌。均会收取费用。不同的扑克场次收费会有不同。":"我们按手收费，只要您坐下，并且完成一手游戏。无论您是否中途弃牌或者打到开牌。均会收取费用。不同的扑克场次收费会有不同。",
          "我在扑克平台观战是否收费？":"我在扑克平台观战是否收费？",
          "观战不会收取费用。":"观战不会收取费用。",
          "如何充值点数？":"如何充值点数？",
          "在PokerWinner里可以使用USDT进行充值，或者找您的代理商购买激活码，并且在PokerWinner里输入使用。":"在PokerWinner里可以使用USDT进行充值，或者找您的代理商购买激活码，并且在PokerWinner里输入使用。",
          "自动代打和只提供策略辅助收费是否有区别？":"自动代打和只提供策略辅助收费是否有区别？",
          "没有区别。收费只和平台与场次有关。":"没有区别。收费只和平台与场次有关。",
          "PokerWinner胜率如何？":"PokerWinner胜率如何？",
          "我们相信数学与大数据，也相信我们的策略比绝大多数玩家更优秀。但考虑到运气成分，我们无法保证您的胜率，请自行评估。":"我们相信数学与大数据，也相信我们的策略比绝大多数玩家更优秀。但考虑到运气成分，我们无法保证您的胜率，请自行评估。",
          "PokerWinner收益不好需要退款":"PokerWinner收益不好需要退款",
          "抱歉，我们不接受退款申请。德州是个长期的数学游戏，短期的胜负波动是非常常见的，如果您无法承受，建议您选择较小的场次。":"抱歉，我们不接受退款申请。德州是个长期的数学游戏，短期的胜负波动是非常常见的，如果您无法承受，建议您选择较小的场次。",
          "PokerWinner如何保证盈利？":"PokerWinner如何保证盈利？",
          "我们无法保证您的盈利，但长期来看，使用AI辅助策略产品是可以盈利的。这个已经经过无数专业德州玩家的考验并证明。":"我们无法保证您的盈利，但长期来看，使用AI辅助策略产品是可以盈利的。这个已经经过无数专业德州玩家的考验并证明。",
          "扑克平台更新了无法使用":"扑克平台更新了无法使用",
          "我们会尽力确保AI产品的稳定性和可用性，如果遇到平台更新无法使用。请联系我们或者耐心等待一段时间。我们会尽快提供扑克平台更新游戏包体。":"我们会尽力确保AI产品的稳定性和可用性，如果遇到平台更新无法使用。请联系我们或者耐心等待一段时间。我们会尽快提供扑克平台更新游戏包体。",
          "PokerWinner没有给我意见":"PokerWinner没有给我意见",
          "抱歉，可能因为网络问题或者我们的服务稳定性偶尔会出现一些策略失去响应。您可以尝试完全退出游戏与PokerWinner并且重新进入游戏。如果问题依然存在，请不要继续进行游戏。反馈给我们或者等待我们修复问题。":"抱歉，可能因为网络问题或者我们的服务稳定性偶尔会出现一些策略失去响应。您可以尝试完全退出游戏与PokerWinner并且重新进入游戏。如果问题依然存在，请不要继续进行游戏。反馈给我们或者等待我们修复问题。",
          "我觉得AI策略不正确，我能否不听意见自己打牌":"我觉得AI策略不正确，我能否不听意见自己打牌",
          "可以，您可以关闭自动代打，并且不理会AI的策略自行操作。下一轮轮到你行动时，AI仍然会根据当前情况给出最新的策略。":"可以，您可以关闭自动代打，并且不理会AI的策略自行操作。下一轮轮到你行动时，AI仍然会根据当前情况给出最新的策略。",
          "为什么我不能打开自动代打功能？":"为什么我不能打开自动代打功能？",
          "前期自动代打仅对部分符合条件的用户开放。如果您需要此功能，可以联系我们或者您的代理商。我们会为您开通。":"前期自动代打仅对部分符合条件的用户开放。如果您需要此功能，可以联系我们或者您的代理商。我们会为您开通。",
          "为什么AI会在不该弃牌的时候放弃？":"为什么AI会在不该弃牌的时候放弃？",
          "AI算法是一套很复杂的理论，它不会单纯输出加注/跟注/弃牌的策略。而是通过混合策略的方式，有概率加注/跟注/弃牌。即使弃牌的概率很低，但也会出现。虽然这不符合人类理解的常识，但从数学角度考虑，此时弃牌的收益和加注/跟注后输掉的概率是相当的。":"AI算法是一套很复杂的理论，它不会单纯输出加注/跟注/弃牌的策略。而是通过混合策略的方式，有概率加注/跟注/弃牌。即使弃牌的概率很低，但也会出现。虽然这不符合人类理解的常识，但从数学角度考虑，此时弃牌的收益和加注/跟注后输掉的概率是相当的。",
          "明明不合理的牌，为什么要下注？":"明明不合理的牌，为什么要下注？",
          "原因有很多，但主要来源基本遵从最小防守频率和最大剥削理论，AI会选择一部分牌进行诈唬，期望获得对手的弃牌收益。":"原因有很多，但主要来源基本遵从最小防守频率和最大剥削理论，AI会选择一部分牌进行诈唬，期望获得对手的弃牌收益。",

        }
      };

}